"""
Django settings for banco project.

Generated by 'django-admin startproject' using Django 5.1.7.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_7femrfpt-jj^w#uc#n@te+%%^5ewota9ahz*0)9x8z@fg!oyy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Apps del proyecto (en orden de dependencia)
    "users",           # Usuarios del sistema y roles
    "clients",         # Clientes del banco
    "accounts",        # Cuentas bancarias
    "cards",           # Tarjetas
    "services",        # Servicios (ANDÉ, ESSAP, etc.)
    "atms",            # Cajeros automáticos
    "transactions",    # Transacciones
    "loans",           # Préstamos
    "core",            # App principal
    "audits",          # Auditoría y bitácora

    # Apps de terceros
    "django_bootstrap5",
    "crispy_forms",
    "crispy_bootstrap5",
    "rest_framework",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'banco.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'banco.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Asuncion'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms config
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Custom User Model
# AUTH_USER_MODEL = 'users.SystemUser'

# Authentication URLs
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Messages Framework
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Email configuration (para desarrollo)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Security settings
SESSION_COOKIE_AGE = 3600  # 1 hora
SESSION_SAVE_EVERY_REQUEST = True

# Configuración de encriptación (para campos sensibles)
ENCRYPTION_KEY = os.environ.get('ENCRYPTION_KEY', 'default-key-for-development-only')

# Configuración de Paraguay (departamentos, ciudades, etc.)
PARAGUAY_DEPARTMENTS = [
    'Concepción', 'San Pedro', 'Cordillera', 'Guairá', 'Caaguazú',
    'Caazapá', 'Itapúa', 'Misiones', 'Paraguarí', 'Alto Paraná',
    'Central', 'Ñeembucú', 'Amambay', 'Canindeyú', 'Presidente Hayes',
    'Alto Paraguay', 'Boquerón', 'Capital'
]

# Configuración de monedas
DEFAULT_CURRENCY = 'PYG'
SUPPORTED_CURRENCIES = ['PYG', 'USD']

# Límites por defecto
DEFAULT_DAILY_TRANSFER_LIMIT = 10000000  # 10M PYG
DEFAULT_DAILY_ATM_LIMIT = 2000000        # 2M PYG